# Generated by Django 3.2.19 on 2023-06-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20230624_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipauthor',
            name='image',
            field=models.ImageField(default='../v1687639484/GetDriveing/blank-profile-picture-gb6ded336d_640_zvs3in.png', upload_to='GetDriveing/'),
        ),
    ]
