# Generated by Django 3.2.19 on 2023-06-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_tipauthor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipauthor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tipauthor',
            name='image',
            field=models.ImageField(default='../blank-profile-picture-gb6ded336d_640_xyxqab.png', upload_to='GetDriveing/'),
        ),
        migrations.AlterField(
            model_name='tipauthor',
            name='privacy_preference',
            field=models.BooleanField(default=False, verbose_name='Would you like your email address to be public?'),
        ),
    ]
