# Generated by Django 3.2.19 on 2023-06-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20230625_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipauthor',
            name='privacy_preference',
            field=models.BooleanField(default=False, verbose_name='Would you like your email address to be publicly available?'),
        ),
    ]
