# Generated by Django 3.2.19 on 2023-06-30 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tips', '0003_rename_author_tip_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('U', 'Unrated'), ('1', 'Very bad'), ('2', 'Not great'), ('3', 'Okay'), ('4', 'Quite useful'), ('5', 'Very useful')], default='Unrated', max_length=30, verbose_name='Rate this tip')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tips.tip')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'tip')},
            },
        ),
    ]
