# Generated by Django 3.2.19 on 2023-06-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='tip_rating',
        ),
    ]
