# Generated by Django 3.2.19 on 2023-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rename_rating_rating_tip_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='tip_rating',
            field=models.IntegerField(),
        ),
    ]
