# Generated by Django 3.2.19 on 2023-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='ability',
            field=models.CharField(choices=[('beginner', 'Beginner+'), ('intermediate', 'Intermediate+'), ('advanced', 'Advanced')], default='beginner', max_length=32, verbose_name='Recommended ability level'),
        ),
        migrations.AddField(
            model_name='tip',
            name='category',
            field=models.CharField(choices=[('drive_pdf', 'Drive/PDFs'), ('sheets', 'Sheets'), ('slides', 'Slides'), ('docs', 'Docs'), ('forms', 'Forms')], default='sheets', max_length=32, verbose_name='Primary category of tip'),
        ),
    ]
