# Generated by Django 3.2.19 on 2023-06-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20230630_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='author',
            new_name='owner',
        ),
    ]
