# Generated by Django 3.2.19 on 2023-07-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_auto_20230720_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='screenshot',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dd4cchm7g/image/upload/v1689846376/GetDriveing/screenshot-default_gbgobl.jpg', upload_to='GetDriveing/', verbose_name='Upload a screenshot if applicable'),
        ),
    ]
