# Generated by Django 3.2.19 on 2023-07-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_alter_tip_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='screenshot',
            field=models.ImageField(blank=True, default='../screenshot-default_gbgobl.jpg', upload_to='GetDriveing/', verbose_name='Upload a screenshot if applicable'),
        ),
    ]
