# Generated by Django 3.2.19 on 2023-06-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_rename_author_tip_owner'),
        ('saved_tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtip',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_saved_tip', to='tips.tip'),
        ),
    ]
